import CA from '../assets/PNG/AC.png';
import CK from '../assets/PNG/KC.png';
import CQ from '../assets/PNG/QC.png';
import CJ from '../assets/PNG/JC.png';
import CT from '../assets/PNG/TC.png';
import C9 from '../assets/PNG/9C.png';
import C8 from '../assets/PNG/8C.png';
import C7 from '../assets/PNG/7C.png';
import C6 from '../assets/PNG/6C.png';
import C5 from '../assets/PNG/5C.png';
import C4 from '../assets/PNG/4C.png';
import C3 from '../assets/PNG/3C.png';
import C2 from '../assets/PNG/2C.png';

import HA from '../assets/PNG/AH.png';
import HK from '../assets/PNG/KH.png';
import HQ from '../assets/PNG/QH.png';
import HJ from '../assets/PNG/JH.png';
import HT from '../assets/PNG/TH.png';
import H9 from '../assets/PNG/9H.png';
import H8 from '../assets/PNG/8H.png';
import H7 from '../assets/PNG/7H.png';
import H6 from '../assets/PNG/6H.png';
import H5 from '../assets/PNG/5H.png';
import H4 from '../assets/PNG/4H.png';
import H3 from '../assets/PNG/3H.png';
import H2 from '../assets/PNG/2H.png';

import SA from '../assets/PNG/AS.png';
import SK from '../assets/PNG/KS.png';
import SQ from '../assets/PNG/QS.png';
import SJ from '../assets/PNG/JS.png';
import ST from '../assets/PNG/TS.png';
import S9 from '../assets/PNG/9S.png';
import S8 from '../assets/PNG/8S.png';
import S7 from '../assets/PNG/7S.png';
import S6 from '../assets/PNG/6S.png';
import S5 from '../assets/PNG/5S.png';
import S4 from '../assets/PNG/4S.png';
import S3 from '../assets/PNG/3S.png';
import S2 from '../assets/PNG/2S.png';

import DA from '../assets/PNG/AD.png';
import DK from '../assets/PNG/KD.png';
import DQ from '../assets/PNG/QD.png';
import DJ from '../assets/PNG/JD.png';
import DT from '../assets/PNG/TD.png';
import D9 from '../assets/PNG/9D.png';
import D8 from '../assets/PNG/8D.png';
import D7 from '../assets/PNG/7D.png';
import D6 from '../assets/PNG/6D.png';
import D5 from '../assets/PNG/5D.png';
import D4 from '../assets/PNG/4D.png';
import D3 from '../assets/PNG/3D.png';
import D2 from '../assets/PNG/2D.png';

const cardMap = new Map();

cardMap.set('ac', CA);
cardMap.set('kc', CK);
cardMap.set('qc', CQ);
cardMap.set('jc', CJ);
cardMap.set('tc', CT);
cardMap.set('9c', C9);
cardMap.set('8c', C8);
cardMap.set('7c', C7);
cardMap.set('6c', C6);
cardMap.set('5c', C5);
cardMap.set('4c', C4);
cardMap.set('3c', C3);
cardMap.set('2c', C2);

cardMap.set('ah', HA);
cardMap.set('kh', HK);
cardMap.set('qh', HQ);
cardMap.set('jh', HJ);
cardMap.set('th', HT);
cardMap.set('9h', H9);
cardMap.set('8h', H8);
cardMap.set('7h', H7);
cardMap.set('6h', H6);
cardMap.set('5h', H5);
cardMap.set('4h', H4);
cardMap.set('3h', H3);
cardMap.set('2h', H2);

cardMap.set('as', SA);
cardMap.set('ks', SK);
cardMap.set('qs', SQ);
cardMap.set('js', SJ);
cardMap.set('ts', ST);
cardMap.set('9s', S9);
cardMap.set('8s', S8);
cardMap.set('7s', S7);
cardMap.set('6s', S6);
cardMap.set('5s', S5);
cardMap.set('4s', S4);
cardMap.set('3s', S3);
cardMap.set('2s', S2);

cardMap.set('ad', DA);
cardMap.set('kd', DK);
cardMap.set('qd', DQ);
cardMap.set('jd', DJ);
cardMap.set('td', DT);
cardMap.set('9d', D9);
cardMap.set('8d', D8);
cardMap.set('7d', D7);
cardMap.set('6d', D6);
cardMap.set('5d', D5);
cardMap.set('4d', D4);
cardMap.set('3d', D3);
cardMap.set('2d', D2);

export default cardMap;
